index:
    path: /index
    controller: App\Controller\IndexPageController::index

index_new:
    path: /
    controller: App\Controller\IndexPageController::newIndex

message:
    path: /message
    controller: App\Controller\MessageController::send

get_data:
    path: /get-data
    controller: App\Controller\GetDataController::getData

write_branch:
    path: /branch/new
    controller: App\Controller\BranchViewController::writeBranch

edit_branch:
    path: /branch/edit/{id}
    controller: App\Controller\BranchViewController::editBranch

delete_branch:
    path: /branch/delete/{id}
    controller: App\Controller\BranchViewController::deleteBranch

brunch_managers:
    path: /branch/{name}
    controller: App\Controller\GetDataController::getBranchManagers



view_all_branches:
    path: /branches
    controller: App\Controller\ViewAllBranchesController::getData

view_all_managers:
    path: /managers
    controller: App\Controller\ViewAllManagersController::getData

create_manager:
    path: /manager/new
    controller: App\Controller\ViewAllManagersController::createManager

update_manager:
    path: /manager/update/{code}
    controller: App\Controller\ViewAllManagersController::updateManager

view_managers_by_branch:
    path: /managers/{id}
    controller: App\Controller\ViewAllManagersController::getManagerByBranch

new_personal_manager:
    path: /manager/{code}
    controller: App\Controller\ViewAllManagersController::getPersonalManager

new_delete_manager:
    path: /delete/{id}
    controller: App\Controller\ViewAllManagersController::deleteManager




personal_manager:
    path: /manager/personal/{code}
    controller: App\Controller\GetDataController::getPersonaManagerSql


set_activity:
    path: /set-activity
    controller: App\Controller\MessageController::setActivity
