index:
    path: /index
    controller: App\Controller\IndexPageController::index

get_data:
    path: /get-data
    controller: App\Controller\GetDataController::getData

write_branch:
    path: /branch/new
    controller: App\Controller\BranchViewController::writeBranch

edit_branch:
    path: /branch/edit/{id}
    controller: App\Controller\BranchViewController::editBranch

delete_branch:
    path: /branch/delete/{id}
    controller: App\Controller\BranchViewController::deleteBranch



write_manager:
    path: /write/manager
    controller: App\Controller\ManagerBaseController::writeManager

edit_manager:
    path: /manager/edit/{id}
    controller: App\Controller\ManagerBaseController::editManager

delete_manager:
    path: /manager/delete/{id}
    controller: App\Controller\ManagerBaseController::deleteManager

personal_manager:
    path: /manager/personal/{name}
    controller: App\Controller\GetDataController::getPersonalManager
