index:
    path: /index
    controller: App\Controller\IndexPageController::index

get_data:
    path: /get-data
    controller: App\Controller\GetDataController::getData

write_branch:
    path: /branch/new
    controller: App\Controller\BranchViewController::writeBranch

edit_branch:
    path: /branch/edit/{id}
    controller: App\Controller\BranchViewController::editBranch

delete_branch:
    path: /branch/delete/{id}
    controller: App\Controller\BranchViewController::deleteBranch

view_all_branches:
    path: /branches
    controller: App\Controller\ViewAllBranchesController::getData




personal_manager:
    path: /manager/personal/{code}
    controller: App\Controller\GetDataController::getPersonaManagerSql
