App\Entity\Manager:
    type: entity
    table: manager
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        surname:
            type: string
            nullable: false
        middleName:
            type: string
            nullable: false
        email:
            type: string
            nullable: true
        photo:
            type: string
            nullable: true
    manyToOne:
        branch:
            targetEntity: App\Entity\Branch
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                branch_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }